### PR TITLE
User page

### PR DESCRIPTION
**Pull request by KyoshiNoda**
## Description
- This story creates the user page UI.
- User page has dummy data for hobby tags waiting on #240 
- I have refactored `User`,`UserContainer` components
- Created a reusable `FriendStatusButton` used in `FindUser` and `UserPage` 

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] ✨ Enhancement
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
- Appoints: #180 

## Mobile & Desktop Screenshots/Recordings

https://github.com/KyoshiNoda/ScheduleFinder/assets/62672803/443138e8-b84f-4332-944b-d81e647b95ab

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by CDDR1** [comment]
I think in the `UserPageBox` component the white background in dark mode contrasts s bit too much. What are your thoughts on changing it to a darker color and white font like this:

Screenshot 2024-01-11 at 10 56 45 AM

**Comment by KyoshiNoda** [comment]
### added changes
image

**Comment by CDDR1** [comment]
> ### added changes
> image

Looks great!

**Review by CDDR1 — APPROVED** [review]
LGTM!

**Pull request merged**
